environement:
  property: I AM PROD

logging:
  level:
    ROOT: INFO
    com.example: INFO

spring:
  application:
    name: minibankc
  datasource:
    url: jdbc:mariadb://localhost:3306/minibankc
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa.hibernate.ddl-auto: create-drop

server:
  port: 8080
