environement:
  property: I AM DEV

logging:
  level:
    ROOT: INFO
#    org.hibernate.SQL: DEBUG
    com.example: DEBUG

spring:
  application:
    name: minibankc
  datasource:
    url: jdbc:h2:mem:minibankc
    #    url: jdbc:h2:file:/data/demo if you  want to store data, uncomment this line
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console.enabled: true # Access to H2 Console with link: http://localhost:8080/h2-console
    console.path: /h2-console
    console.settings.trace: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080
